### ISSUE TITLE
Избавиться от закомментированного кода

### ISSUE THREAD

**Issue by umpteenthdev** [CasperKHV/Weather#10]
В проекте очень много комментариев. 
Нужно удалить явно закомментированный код. 
Например, такой:

```kotlin
//        adapter = new NoteAdapter(noteDataReader);
//        adapter.setOnMenuItemClickListener(new NoteAdapter.OnMenuItemClickListener() {
//            @Override
//            public void onItemEditClick(CityNote note) {
//                editElement(note);
//            }
//
//            @Override
//            public void onItemDeleteClick(CityNote note) {
//                deleteElement(note);
//            }
//        });
//        citiesCategoriesRecyclerView.setAdapter(adapter);

```

Также нужно сделать ревью всех имеющихся текстовых комментариев.
Например, следующий комментарий не имеет смысла. По названию переменной и её типу и так понятно что это за переменная и зачем она нужна
```kotlin
    private var adapter // Адаптер для RecyclerView
            : MyAdapter? = null
```
Помимо этого, комментарии в подобных местах не пишут. Обычно, если добавляется комментарий к свойству, то он пишется выше свойства или в документации класса. Например так:
```kotlin
/**
 * @property adapter Адаптер для RecyclerView
 */
class CitiesListFragment : Fragment() {
    // Другой вариант комментария
    private var adapter: MyAdapter? = null // Ещё один корректный вариант комментария
    // ...
}
```

Формат взаимодействия остается как и раньше - сделал ветку с осмысленным именем, сделал PR, прикрепил его к issue, прошел ревью, смержил, живём дальше. Думаю, больше описывать это не буду подробно.

- [x] Удалить закомментированный код
- [x] Удалить избыточные текстовые комментарии

**Comment by CasperKHV** [comment]
@umpteenthdev готов к ревью.
