### ISSUE TITLE
Переименовать проект и пакеты в проекте

### ISSUE THREAD

**Issue by umpteenthdev** [CasperKHV/Weather#9]
- [x] Придумать имя проекта, отражающее его суть
- [x] Предложить это имя в комментариях и описать почему выбрано именно оно
- [x] Согласовать новое имя проекта
- [x] Изменить имя проекта в `rootProject.name` поле
- [x] Придумать новое имя пакета вместо `com.example.coloreffect`. Обычно оно основывается на пути к сайту компании. В нашем случае можно использовать никнейм пользователя. Например `com.casperkhv.<...>`
- [x] Изменить имена пакетов в проекте через `ctrl + F6` в дереве проекта
- [x] Сделать PR и прикрепить его к этой issue
- [x] Переименовать проект на GitHub

**Comment by CasperKHV** [comment]
Предлагаю имя "Feels like Weather". Строка "ощущается как" - одна из самых востребованных в погодных приложениях, ибо учитывает сочетание разных погодных факторов. Также такое название можно перевести как "Похоже на погоду", что придаёт уместной ироничности, учитывая учебный статус проекта.

**Comment by umpteenthdev** [comment]
> @umpteenthdev Предлагаю имя "Feels like Weather". Строка "ощущается как" - одна из самых востребованных в погодных приложениях, ибо учитывает сочетание разных погодных факторов. Также такое название можно перевести как "Похоже на погоду", что придаёт уместной ироничности, учитывая учебный статус проекта.

Мне кажется, что здесь из-за английского может быть неоднозначное понимание. `Feel like` имеет кучу значений и в контексте использования с существительным это часто обозначает желание. Например, `I feel like Chinese food` означает, что я хочу китайской еды, а не то, что я китайская еда. 
Как вариант, можно модифицировать в `Feels like rain`, что будет означать `Кажется дождь собирается`. К мультфильму отсылки не сделает, но это устойчивое выражение.
Подробнее можно тут глянуть https://dictionary.cambridge.org/dictionary/english/feel-like
Если не нравится, то накидывай ещё вариантов.

**Comment by CasperKHV** [comment]
> > @umpteenthdev Предлагаю имя "Feels like Weather". Строка "ощущается как" - одна из самых востребованных в погодных приложениях, ибо учитывает сочетание разных погодных факторов. Также такое название можно перевести как "Похоже на погоду", что придаёт уместной ироничности, учитывая учебный статус проекта.
> 
> Мне кажется, что здесь из-за английского может быть неоднозначное понимание. `Feel like` имеет кучу значений и в контексте использования с существительным это часто обозначает желание. Например, `I feel like Chinese food` означает, что я хочу китайской еды, а не то, что я китайская еда. Как вариант, можно модифицировать в `Feels like rain`, что будет означать `Кажется дождь собирается`. К мультфильму отсылки не сделает, но это устойчивое выражение. Подробнее можно тут глянуть https://dictionary.cambridge.org/dictionary/english/feel-like Если не нравится, то накидывай ещё вариантов.

Предлагаю нейтральное название - "Weather".

**Comment by umpteenthdev** [comment]
> > > @umpteenthdev Предлагаю имя "Feels like Weather". Строка "ощущается как" - одна из самых востребованных в погодных приложениях, ибо учитывает сочетание разных погодных факторов. Также такое название можно перевести как "Похоже на погоду", что придаёт уместной ироничности, учитывая учебный статус проекта.
> > 
> > 
> > Мне кажется, что здесь из-за английского может быть неоднозначное понимание. `Feel like` имеет кучу значений и в контексте использования с существительным это часто обозначает желание. Например, `I feel like Chinese food` означает, что я хочу китайской еды, а не то, что я китайская еда. Как вариант, можно модифицировать в `Feels like rain`, что будет означать `Кажется дождь собирается`. К мультфильму отсылки не сделает, но это устойчивое выражение. Подробнее можно тут глянуть https://dictionary.cambridge.org/dictionary/english/feel-like Если не нравится, то накидывай ещё вариантов.
> 
> Предлагаю нейтральное название - "Weather".

Договорились 👍
